FROM python:3.11.10-alpine3.20

RUN apk add --no-cache \
    gcc \
    musl-dev \
    postgresql-dev \
    libpq

WORKDIR /app

COPY Pipfile Pipfile.lock /app/

RUN pip install pipenv 
RUN pipenv install

COPY . /app/

CMD pipenv run python manage.py migrate && \
    pipenv run python manage.py collectstatic --no-input && \
    pipenv run gunicorn -bind 0.0.0.0:2727 storefront.wsgi



