FROM python:3.11.10-alpine3.20

RUN apk add --no-cache \
    gcc \
    musl-dev \
    postgresql-dev \
    libpq

WORKDIR /app

COPY Pipfile Pipfile.lock /app/

RUN pip install pipenv && pipenv install

COPY . /app/

CMD pipenv run python manage.py migrate && pipenv run python manage.py runserver

