# Generated by Django 5.1.1 on 2024-09-30 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='expected_death',
            field=models.DateField(blank=True, null=True),
        ),
    ]
