# Generated by Django 5.1.1 on 2024-10-08 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0002_customer_expected_death'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='expected_death',
        ),
    ]
